name: Deploy to EC2

# Hangi durumda çalışacağını belirtiyoruz. Burada 'main' branşına yapılan push'lar ile tetiklenecek.
on:
  push:
    branches:
      - main  # Ana branşın adını buraya yazın, 'master' da olabilir.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Kodu GitHub'dan çekmek için

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3  # SSH bağlantısı için
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r * ubuntu@your-ec2-ip:/home/ubuntu/app

    - name: Install dependencies and restart application
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@your-ec2-ip << 'EOF'
        cd /home/ubuntu/app
        pip3 install -r requirements.txt  # Bağımlılıkları kur
        pkill -f app.py || true           # Eski uygulamayı sonlandır
        nohup python3 app.py &            # Uygulamayı yeniden başlat
        EOF
