name: Deploy to EC2

on:
  push:
    branches:
      - main  # Ana branch'ın adını doğru yazdığınızdan emin olun. Örneğin 'master' veya 'main'.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r * ubuntu@your-ec2-ip:/home/ubuntu/app

    - name: Install dependencies and restart application
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@your-ec2-ip << 'EOF'
        cd /home/ubuntu/app
        pip3 install -r requirements.txt
        pkill -f app.py || true
        nohup python3 app.py &
        EOF
